name: Deploy to Cloudflare Worker (backend)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      FRONTEND_URL: ${{ vars.FRONTEND_URL }}
      TIMEZONE: ${{ vars.TIMEZONE }}
      D1_DATABASE_ID: ${{ vars.D1_DATABASE_ID }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install project dependencies
        run: cd backend && npm install

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Update wrangler config with environment variables && delete secrets
        run: |
          cd backend
          jq \
            --arg fe "${{ vars.FRONTEND_URL }}" \
            --arg tz "${{ vars.TIMEZONE }}" \
            --arg dbid "${{ vars.D1_DATABASE_ID }}" \
            '.vars.FRONTEND_URL = $fe | .vars.TIMEZONE = $tz | .d1_databases[0].database_id = $dbid | del(.vars.JWT_SECRET)' \
            wrangler.jsonc > wrangler.local.jsonc

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: cd backend && wrangler deploy --config wrangler.local.jsonc

      - name: Set secrets in Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          cd backend && echo "${{ secrets.JWT_SECRET }}" | wrangler secret put JWT_SECRET
